=== taraknasi/MyXMLProject/annuaire.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!ELEMENT annuaire (personne)+>
<!ELEMENT personne (prenom,nom,telephone+)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>

=== taraknasi/MyXMLProject/annuaire.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE annuaire SYSTEM "annuaire.dtd">
<annuaire>
  <personne>
    <prenom>Alain</prenom>
    <nom>Bouchard</nom>
    <telephone>06 00 00 00 01</telephone>
  </personne>
  <personne>
    <prenom>Franck</prenom>
    <nom>Morin</nom>
    <telephone>06 00 00 00 02</telephone>
  </personne>
  <personne>
    <prenom>Christian</prenom>
    <nom>Gauthier</nom>
    <telephone>06 00 00 00 03</telephone>
  </personne>
  <personne>
    <prenom>Martin</prenom>
    <nom>Lavoie</nom>
    <telephone>06 00 00 00 04</telephone>
  </personne>
</annuaire>
